name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        npm audit fix || true  # 如果有不能自動修復的漏洞，流程會繼續執行

    - name: Build project
      run: npm run build

    - name: Generate static files
      run: npm run generate

    - name: Upload static files as artifact
      uses: actions/upload-artifact@v3
      with:
        name: static-files
        path: .output/public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .output/public
